steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$flaskdemo1-443410/flask-app:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$flaskdemo1-443410/flask-app:$COMMIT_SHA']
images:
  - 'gcr.io/$flaskdemo1-443410/flask-app:$COMMIT_SHA'





steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$flaskdemo1-443410/flask-app:v1', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$flaskdemo1-443410_ID/flask-app:v1']

