apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app1
  template:
    metadata:
      labels:
        app: flask-app1
    spec:
      containers:
      - name: flask-app1
        image: gcr.io/flaskdemo2-443815/flask-app1:v3
        ports:
        - containerPort: 5000
   
   
   
   
   
